server:
  port: 8060
  forward-headers-strategy: framework

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /online-bank/auth/**
          filters:
            - ContextPathRewritePath=/online-bank/auth/(?<path>.*), /$\{path}
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: accounting-service
          uri: lb://accounting-service
          predicates:
            - Path=/account/**, /online-bank/account/**
          filters:
            - ContextPathRewritePath=/online-bank/account/(?<path>.*), /$\{path}
            - RewritePath=/account/(?<path>.*), /$\{path}

    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: optional:configserver:http://localhost:8888

app:
  jwt:
    secret: ${JWT_SECRET:U2FsdGVkX1+XrCkUhz7gU6SzP4E9dyDq0j6f6vOwA1jP4Xl6H3oc61hZGz7Fx0T7}

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
